stages:
  - build
  - test
  - sonarqube-check
  - package
  - trigger_deploy

build:
  stage: build
  script:
    - ./gradlew assemble --no-daemon

test:
  stage: test
  script:
    - ./gradlew test --no-daemon

sonarqube-check:
  stage: sonarqube-check
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
    SONAR_HOST_URL: "http://localhost:9000"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - ./gradlew build jacocoTestReport sonar --no-daemon -Dsonar.qualitygate.wait=true
  allow_failure: true

package:
  stage: package
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_TOKEN
    - echo 'login'
    - docker build -t $DOCKER_HUB_USERNAME/skytrack:latest -t $DOCKER_HUB_USERNAME/skytrack:$CI_COMMIT_SHORT_SHA .
    - echo 'build'
    - docker push $DOCKER_HUB_USERNAME/skytrack:latest
    - echo 'push'
    - docker push $DOCKER_HUB_USERNAME/skytrack:$CI_COMMIT_SHORT_SHA
    - echo 'push 2'

trigger_deploy:
  stage: trigger_deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  trigger:
    project: I547761/skytrack-infra
    branch: main