stages:
- build
- test
- sonarqube-check

build:
  stage: build
  script:
    - .\gradlew.bat assemble --no-daemon

test:
  stage: test
  script:
    - .\gradlew.bat test --no-daemon

sonarqube-check:
  stage: sonarqube-check
  script:
    - echo "Setting up CI"
