stages:
- build
- test
- sonarqube-check

build:
  stage: build
  script:
    - ./gradlew assemble --no-daemon

test:
  stage: test
  script:
    - ./gradlew test assemble --no-daemon

sonarqube-check:
  stage: sonarqube-check
  script:
    - echo "Setting up CI"
