spring:
  datasource:
    url: ${Db_url}
    username: ${Db_username}
    password: ${Db_password}
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

sentry:
  dsn: https://3c587baa3f7b670fa78794a0d924b298@o4511095744954368.ingest.de.sentry.io/4511095771824208
  traces-sample-rate: 1.0

logging:
  level:
    skytrack: INFO

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 86400000

duffel:
  api:
    key: ${DUFFEL_API_KEY}

frankfurter:
  base_url: ${FRANKFURT_URL}

app:
  base-url: ${BASE_URL}
  cors:
    allowed-origins: ${ALLOWED_ORIGINS}